version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - static:/var/www/app/public/static
      - media:/var/www/app/media
      - tmp:/tmp
    depends_on:
      - app

  app:
    build: .
    image: altotech
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata room.json &&
             python manage.py loaddata video.json &&
             gunicorn backend.wsgi:application -b unix:/tmp/gunicorn.sock"
    env_file: .env-sample
    volumes:
      # - static:/app/public/static
      - media:/app/media
      - tmp:/tmp
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    env_file: .env-sample
    ports:
      - 5432:5432

volumes:
  # static:
  media:
  tmp:
